# Déclencheur : la pipeline s'exécute automatiquement lors d'un push sur la branche main
trigger:
- main

# Utilisation de ton propre PC comme Agent de build (Self-hosted Agent)
pool:
  name: 'Default'

variables:
  # NOM DE LA SERVICE CONNECTION (L'agent l'utilise pour se connecter à Azure)
  dockerRegistryServiceConnection: 'MyAzureConn_2'
  
  # NOM DU REPOSITORY (Le dossier dans ACR où l'image sera stockée)
  imageRepository: 'mon-app-front'
  
  # Tag unique pour chaque build
  tag: '$(Build.BuildId)'

steps:
# Étape de construction (Build) et d'envoi (Push) de l'image vers Azure Container Registry
- task: Docker@2
  displayName: 'Build and Push Image to ACR'
  inputs:
    command: 'buildAndPush'
    # Utilisation du nom du repo défini dans les variables
    repository: $(imageRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    # ICI : On met obligatoirement la Service Connection (L'authentification)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
      latest