# Déclencheur : la pipeline s'exécute automatiquement lors d'un push sur la branche main
trigger:
- main

# Utilisation de ton propre PC comme Agent de build (Self-hosted Agent)
pool:
  name: 'Default'

variables:
  # Nom de la Service Connection pour le Docker Registry
  dockerRegistryServiceConnection: 'MyAzureConn_2'
  
  # Nom du serveur de connexion ACR
  containerRegistry: 'cloudazure1.azurecr.io' 
  
  # Nom du repository pour l'image Docker
  imageRepository: 'mon-app-front'
  
  # Tag unique pour chaque build
  tag: '$(Build.BuildId)'

steps:
# Étape de construction (Build) et d'envoi (Push) de l'image vers Azure Container Registry
- task: Docker@2
  displayName: 'Build and Push Image to ACR'
  inputs:
    command: 'buildAndPush'
    repository: $(imageRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    # Utilisation de la Service Connection pour l'authentification
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
      latest